## Produces the following output:
  # log-log density plot of all contig lengths
  # basic statistics (no. of contigs, N50, N90, no. above a certain len e.g. 5K)
  # simple rank or jitter plot of 100 largest contigs

#setwd([insert wd here])

# reads in comma-separated contig lengths (generated by 'contig_stats.py')
pilluana_lengths = scan("./pilluana.contigs_lengths", sep = ",")
pilluana_lengths = sort(pilluana_lengths, decreasing = TRUE)
maras3_lengths = scan("./maras3.contigs_lengths", sep = ",")
maras3_lengths = sort(maras3_lengths, decreasing = TRUE)

## NB: all contigs < 500 bp have been removed from assembly output, so this will increase N50
## find the total length of all reads, and use 1/2 that to calculate the true N50
# length(pilluana_lengths) == 857,886
# sum(pilluana_lengths)/1000000 == 933 mb
# length(maras3_lengths) == 1,437,380
# sum(maras3_lengths)/1000000 == 1214 mb
# sum(pilluana_lengths)/length(pilluana_lengths) == 1087.416
# sum(maras3_lengths)/length(maras3_lengths) == 844.3821
# max(pilluana_lengths) == 223,333 (size of a small bacterial genome)
# max(maras3_lengths) == 243,827
# sum(pilluana_lengths >= 5000) == 14,700
# sum(maras3_lengths > 5000) == 6,365
## sum(pilluana_lengths[pilluana_lengths > 5000])/1000000 == 159.42 Mbp
## sum(maras3_lengths[maras3_lengths > 5000])/1000000 == 55.97 Mbp
# while (sum(maras3_lengths > x) > sum(pilluana_lengths > x)){x = x+1}
#   x = 1221 (so pilluana has more contigs above 1221 nt.)
# pilluana_lengths[cumsum(pilluana_lengths) > (sum(pilluana_lengths)/2)][1]
#   N50 == 1104
# pilluana_lengths[cumsum(pilluana_lengths) > (sum(pilluana_lengths)*0.9)][1]
#   N90 == 568
# pilluana_lengths[cumsum(pilluana_lengths) > (sum(pilluana_lengths)*0.1)][1]
#   N10 == 9761
# maras3_lengths[cumsum(maras3_lengths) > (sum(maras3_lengths)/2)][1]
#   N50 == 785
# maras3_lengths[cumsum(maras3_lengths) > (sum(maras3_lengths)/2)][1]
#   N90 == 543
# maras3_lengths[cumsum(maras3_lengths) > (sum(maras3_lengths)*0.1)][1]
#   N10 == 2673
##
# graph of Nx vs length...
# or more easily interpreted graph: length vs no. of contigs above this length

x = seq(1000,50000,1000)
y_pill = rep(0, 50)
i = 1
for (item in x){
  y_pill[i] = sum(pilluana_lengths>=item)
  i = i+1
}
y_mar = rep(0, 50)
i = 1
for (item in x){
  y_mar[i] = sum(maras3_lengths>=item)
  i = i+1
}

plot(x, y_mar, log = 'y', col = 'brown')
# make y-axis scale more readable
# make x-axis scale smaller (at least show lines for each 1000)
points(x, y_pill, col = 'green')

##

hist(log10(pilluana_lengths), xlim = c(min(log10(pilluana_lengths)), 4))
hist(log10(maras3_lengths), xlim = c(min(log10(maras3_lengths)), 4))

hist(pilluana_lengths, xlim = c(min(pilluana_lengths), max(pilluana_lengths)), breaks = 100)

# ggplot is better - plot background has faint axis lines, so easier comparisons can be made
png("log-log_contig_density.png")
plot(density(log10(pilluana_lengths)), log = 'y', col = "green",
     xlim = c(min(log10(pilluana_lengths)), max(log10(pilluana_lengths))),
     main = "log-log plot of contig length density",
     xlab = expression("log"[10]*"(contig length)"))
abline(v = log10(1104), lty = 2, col = "green")
lines(density(log10(maras3_lengths)), log = 'y', col = "brown")
abline(v = log10(785), col = "brown", lty = 2)
text(x = log10(785))
legend('topright', c("pilluana", "maras3"), lty = 1, col = c("green", "brown"))
legend('bottom', c("pilluana N50", "maras3 N50"), lty = 2, col = c("green", "brown"))
dev.off()

# density of log10 lengths
plot(density(log10(pilluana_lengths)), 
     xlim = c(min(log10(pilluana_lengths)), max(log10(pilluana_lengths))),
     ylim = c(0, 4.5),
     main = "density plot of contig lengths",
     xlab = "log10(contig length)")
abline(v = log10(1104))
lines(density(log10(maras3_lengths)),
      col = "red")
abline(v = log10(785), col = "red")

# log10 density of lengths
plot(density(pilluana_lengths), log = 'y', 
     xlim = c(min(pilluana_lengths), max(pilluana_lengths)),
     main = "plot of contig length density",
     xlab = "contig length")
#abline(v = 1104)
lines(density(maras3_lengths), log = 'y',
      col = "red")
#abline(v = 785, col = "red")
legend('topright', c("pilluana", "maras3"), lty = 1, col = c("black", "red"))

## extract new vectors with all 1k+ lengths, 2k+ lengths, 5k+ lengths, 10K plus lengths
## a few successive density plots will be like 'magnifying/blowing up' the top end of the distribution
## also, extract the top 100 or so lengths and do a point plot

maras3_lengths_2k = maras3_lengths[1:(sum(maras3_lengths >= 2000))]
maras3_lengths_5k = maras3_lengths[1:(sum(maras3_lengths >= 5000))]
maras3_lengths_10k = maras3_lengths[1:(sum(maras3_lengths >= 10000))]
maras3_lengths_20k = maras3_lengths[1:(sum(maras3_lengths >= 20000))]


pilluana_lengths_2k = pilluana_lengths[1:(sum(pilluana_lengths >= 2000))]
pilluana_lengths_5k = pilluana_lengths[1:(sum(pilluana_lengths >= 5000))]
pilluana_lengths_10k = pilluana_lengths[1:(sum(pilluana_lengths >= 10000))]
pilluana_lengths_20k = pilluana_lengths[1:(sum(pilluana_lengths >= 20000))]


plot(density(maras3_lengths_20k), 
     xlim = c(min(maras3_lengths_20k), max(maras3_lengths_20k)),
     ylim = c(0, max(density(pilluana_lengths_20k)$y)),
     #xlim = c(0, 100000),
     main = "density plot of contig lengths above 20k",
     xlab = "contig length")
lines(density(pilluana_lengths_20k),
      col = "red")

# maras should be plotted first, because the peak density is higher

# 2 rugplots of 20k+ contigs
plot(x = rep(1, length(maras3_lengths_20k)), y = maras3_lengths_20k, col = "black", pch=3,
     xlim = c(0.5, 2.5))
points(x = rep(2, length(pilluana_lengths_20k)), y = pilluana_lengths_20k, col = "red", pch=3)

# 2 rugplots of top 100 contigs for both samples
pilluana_lengths_top100 = pilluana_lengths[1:100]
maras3_lengths_top100 = maras3_lengths[1:100]
top100 = data.frame(maras3_lengths_top100, pilluana_lengths_top100)

plot(x = rep("maras3", 100), y = maras3_lengths_top100/1000, col = "black", pch = 3,
     #xlim = c(0.5, 2.5))
     xlab = "sample",
     ylab = "contig length (kb)")
points(x = rep("pilluana", 100), y = pilluana_lengths_top100/1000, col = "red", pch = 3)

png("top100contigs.png")
plot(maras3_lengths_top100/1000, pch = '-', xlab = "rank (descending)", 
     ylab = "contig length (kb)",
     col = "brown",
     main = "100 longest contigs from pilluana and maras3 assemblies",
     ylim = c(0,250),
     cex.main = 1, cex.lab = 0.9, cex.axis = .9)
points(pilluana_lengths_top100/1000, pch = '-', col = "green")
legend('topright', c("pilluana", "maras3"), lty = 1, col = c("green", "brown"))
dev.off()
